//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship5", "measure", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CafeSystem.measure), "ingridient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.ingridient), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship8", "ingridient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.ingridient), "recipe_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.recipe_stuff), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship9", "recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.recipe), "recipe_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.recipe_stuff), true)]

#endregion

namespace CafeSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cafesystemEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cafesystemEntities1 object using the connection string found in the 'cafesystemEntities1' section of the application configuration file.
        /// </summary>
        public cafesystemEntities1() : base("name=cafesystemEntities1", "cafesystemEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cafesystemEntities1 object.
        /// </summary>
        public cafesystemEntities1(string connectionString) : base(connectionString, "cafesystemEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cafesystemEntities1 object.
        /// </summary>
        public cafesystemEntities1(EntityConnection connection) : base(connection, "cafesystemEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ingridient> ingridient
        {
            get
            {
                if ((_ingridient == null))
                {
                    _ingridient = base.CreateObjectSet<ingridient>("ingridient");
                }
                return _ingridient;
            }
        }
        private ObjectSet<ingridient> _ingridient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<measure> measure
        {
            get
            {
                if ((_measure == null))
                {
                    _measure = base.CreateObjectSet<measure>("measure");
                }
                return _measure;
            }
        }
        private ObjectSet<measure> _measure;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recipe> recipe
        {
            get
            {
                if ((_recipe == null))
                {
                    _recipe = base.CreateObjectSet<recipe>("recipe");
                }
                return _recipe;
            }
        }
        private ObjectSet<recipe> _recipe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recipe_stuff> recipe_stuff
        {
            get
            {
                if ((_recipe_stuff == null))
                {
                    _recipe_stuff = base.CreateObjectSet<recipe_stuff>("recipe_stuff");
                }
                return _recipe_stuff;
            }
        }
        private ObjectSet<recipe_stuff> _recipe_stuff;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ingridient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToingridient(ingridient ingridient)
        {
            base.AddObject("ingridient", ingridient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the measure EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomeasure(measure measure)
        {
            base.AddObject("measure", measure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recipe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecipe(recipe recipe)
        {
            base.AddObject("recipe", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recipe_stuff EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecipe_stuff(recipe_stuff recipe_stuff)
        {
            base.AddObject("recipe_stuff", recipe_stuff);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="ingridient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ingridient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ingridient object.
        /// </summary>
        /// <param name="ingridients_id">Initial value of the ingridients_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static ingridient Createingridient(global::System.Int32 ingridients_id, global::System.String name)
        {
            ingridient ingridient = new ingridient();
            ingridient.ingridients_id = ingridients_id;
            ingridient.name = name;
            return ingridient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ingridients_id
        {
            get
            {
                return _ingridients_id;
            }
            set
            {
                if (_ingridients_id != value)
                {
                    Oningridients_idChanging(value);
                    ReportPropertyChanging("ingridients_id");
                    _ingridients_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ingridients_id");
                    Oningridients_idChanged();
                }
            }
        }
        private global::System.Int32 _ingridients_id;
        partial void Oningridients_idChanging(global::System.Int32 value);
        partial void Oningridients_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> measure_id
        {
            get
            {
                return _measure_id;
            }
            set
            {
                Onmeasure_idChanging(value);
                ReportPropertyChanging("measure_id");
                _measure_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("measure_id");
                Onmeasure_idChanged();
            }
        }
        private Nullable<global::System.Int32> _measure_id;
        partial void Onmeasure_idChanging(Nullable<global::System.Int32> value);
        partial void Onmeasure_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship5", "measure")]
        public measure measure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<measure> measureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<measure>("cafesystemModel.Relationship5", "measure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship8", "recipe_stuff")]
        public EntityCollection<recipe_stuff> recipe_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipe_stuff>("cafesystemModel.Relationship8", "recipe_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipe_stuff>("cafesystemModel.Relationship8", "recipe_stuff", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="measure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class measure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new measure object.
        /// </summary>
        /// <param name="measure_id">Initial value of the measure_id property.</param>
        /// <param name="measure1">Initial value of the measure1 property.</param>
        public static measure Createmeasure(global::System.Int32 measure_id, global::System.String measure1)
        {
            measure measure = new measure();
            measure.measure_id = measure_id;
            measure.measure1 = measure1;
            return measure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 measure_id
        {
            get
            {
                return _measure_id;
            }
            set
            {
                if (_measure_id != value)
                {
                    Onmeasure_idChanging(value);
                    ReportPropertyChanging("measure_id");
                    _measure_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("measure_id");
                    Onmeasure_idChanged();
                }
            }
        }
        private global::System.Int32 _measure_id;
        partial void Onmeasure_idChanging(global::System.Int32 value);
        partial void Onmeasure_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String measure1
        {
            get
            {
                return _measure1;
            }
            set
            {
                Onmeasure1Changing(value);
                ReportPropertyChanging("measure1");
                _measure1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("measure1");
                Onmeasure1Changed();
            }
        }
        private global::System.String _measure1;
        partial void Onmeasure1Changing(global::System.String value);
        partial void Onmeasure1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship5", "ingridient")]
        public EntityCollection<ingridient> ingridient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ingridient>("cafesystemModel.Relationship5", "ingridient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ingridient>("cafesystemModel.Relationship5", "ingridient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recipe object.
        /// </summary>
        /// <param name="recipe_id">Initial value of the recipe_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static recipe Createrecipe(global::System.Int32 recipe_id, global::System.String name)
        {
            recipe recipe = new recipe();
            recipe.recipe_id = recipe_id;
            recipe.name = name;
            return recipe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_id
        {
            get
            {
                return _recipe_id;
            }
            set
            {
                if (_recipe_id != value)
                {
                    Onrecipe_idChanging(value);
                    ReportPropertyChanging("recipe_id");
                    _recipe_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_id");
                    Onrecipe_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_id;
        partial void Onrecipe_idChanging(global::System.Int32 value);
        partial void Onrecipe_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship9", "recipe_stuff")]
        public EntityCollection<recipe_stuff> recipe_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipe_stuff>("cafesystemModel.Relationship9", "recipe_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipe_stuff>("cafesystemModel.Relationship9", "recipe_stuff", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="recipe_stuff")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recipe_stuff : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recipe_stuff object.
        /// </summary>
        /// <param name="ingridients_id">Initial value of the ingridients_id property.</param>
        /// <param name="recipe_id">Initial value of the recipe_id property.</param>
        /// <param name="recipe_stuff_id">Initial value of the recipe_stuff_id property.</param>
        /// <param name="count">Initial value of the count property.</param>
        public static recipe_stuff Createrecipe_stuff(global::System.Int32 ingridients_id, global::System.Int32 recipe_id, global::System.Int32 recipe_stuff_id, global::System.Int32 count)
        {
            recipe_stuff recipe_stuff = new recipe_stuff();
            recipe_stuff.ingridients_id = ingridients_id;
            recipe_stuff.recipe_id = recipe_id;
            recipe_stuff.recipe_stuff_id = recipe_stuff_id;
            recipe_stuff.count = count;
            return recipe_stuff;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ingridients_id
        {
            get
            {
                return _ingridients_id;
            }
            set
            {
                if (_ingridients_id != value)
                {
                    Oningridients_idChanging(value);
                    ReportPropertyChanging("ingridients_id");
                    _ingridients_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ingridients_id");
                    Oningridients_idChanged();
                }
            }
        }
        private global::System.Int32 _ingridients_id;
        partial void Oningridients_idChanging(global::System.Int32 value);
        partial void Oningridients_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_id
        {
            get
            {
                return _recipe_id;
            }
            set
            {
                if (_recipe_id != value)
                {
                    Onrecipe_idChanging(value);
                    ReportPropertyChanging("recipe_id");
                    _recipe_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_id");
                    Onrecipe_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_id;
        partial void Onrecipe_idChanging(global::System.Int32 value);
        partial void Onrecipe_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_stuff_id
        {
            get
            {
                return _recipe_stuff_id;
            }
            set
            {
                if (_recipe_stuff_id != value)
                {
                    Onrecipe_stuff_idChanging(value);
                    ReportPropertyChanging("recipe_stuff_id");
                    _recipe_stuff_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_stuff_id");
                    Onrecipe_stuff_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_stuff_id;
        partial void Onrecipe_stuff_idChanging(global::System.Int32 value);
        partial void Onrecipe_stuff_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private global::System.Int32 _count;
        partial void OncountChanging(global::System.Int32 value);
        partial void OncountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship8", "ingridient")]
        public ingridient ingridient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ingridient> ingridientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship9", "recipe")]
        public recipe recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipe> recipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
