//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship10", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.department), "worker", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.worker), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship15", "food_category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CafeSystem.food_category), "recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.recipe), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship14", "supply", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CafeSystem.supply), "ingridient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.ingridient), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship5", "measure", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CafeSystem.measure), "ingridient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.ingridient), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship8", "ingridient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.ingridient), "recipe_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.recipe_stuff), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship19", "recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.recipe), "order_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.order_stuff), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship20", "ordert", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.ordert), "order_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.order_stuff), true)]
[assembly: EdmRelationshipAttribute("cafesystemModel", "Relationship9", "recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CafeSystem.recipe), "recipe_stuff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CafeSystem.recipe_stuff), true)]

#endregion

namespace CafeSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cafesystemEntities4 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cafesystemEntities4 object using the connection string found in the 'cafesystemEntities4' section of the application configuration file.
        /// </summary>
        public cafesystemEntities4() : base("name=cafesystemEntities4", "cafesystemEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cafesystemEntities4 object.
        /// </summary>
        public cafesystemEntities4(string connectionString) : base(connectionString, "cafesystemEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cafesystemEntities4 object.
        /// </summary>
        public cafesystemEntities4(EntityConnection connection) : base(connection, "cafesystemEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<department> department
        {
            get
            {
                if ((_department == null))
                {
                    _department = base.CreateObjectSet<department>("department");
                }
                return _department;
            }
        }
        private ObjectSet<department> _department;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<food_category> food_category
        {
            get
            {
                if ((_food_category == null))
                {
                    _food_category = base.CreateObjectSet<food_category>("food_category");
                }
                return _food_category;
            }
        }
        private ObjectSet<food_category> _food_category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ingridient> ingridient
        {
            get
            {
                if ((_ingridient == null))
                {
                    _ingridient = base.CreateObjectSet<ingridient>("ingridient");
                }
                return _ingridient;
            }
        }
        private ObjectSet<ingridient> _ingridient;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<measure> measure
        {
            get
            {
                if ((_measure == null))
                {
                    _measure = base.CreateObjectSet<measure>("measure");
                }
                return _measure;
            }
        }
        private ObjectSet<measure> _measure;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order_stuff> order_stuff
        {
            get
            {
                if ((_order_stuff == null))
                {
                    _order_stuff = base.CreateObjectSet<order_stuff>("order_stuff");
                }
                return _order_stuff;
            }
        }
        private ObjectSet<order_stuff> _order_stuff;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ordert> ordert
        {
            get
            {
                if ((_ordert == null))
                {
                    _ordert = base.CreateObjectSet<ordert>("ordert");
                }
                return _ordert;
            }
        }
        private ObjectSet<ordert> _ordert;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recipe> recipe
        {
            get
            {
                if ((_recipe == null))
                {
                    _recipe = base.CreateObjectSet<recipe>("recipe");
                }
                return _recipe;
            }
        }
        private ObjectSet<recipe> _recipe;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recipe_stuff> recipe_stuff
        {
            get
            {
                if ((_recipe_stuff == null))
                {
                    _recipe_stuff = base.CreateObjectSet<recipe_stuff>("recipe_stuff");
                }
                return _recipe_stuff;
            }
        }
        private ObjectSet<recipe_stuff> _recipe_stuff;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<supply> supply
        {
            get
            {
                if ((_supply == null))
                {
                    _supply = base.CreateObjectSet<supply>("supply");
                }
                return _supply;
            }
        }
        private ObjectSet<supply> _supply;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<worker> worker
        {
            get
            {
                if ((_worker == null))
                {
                    _worker = base.CreateObjectSet<worker>("worker");
                }
                return _worker;
            }
        }
        private ObjectSet<worker> _worker;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the department EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartment(department department)
        {
            base.AddObject("department", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the food_category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofood_category(food_category food_category)
        {
            base.AddObject("food_category", food_category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ingridient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToingridient(ingridient ingridient)
        {
            base.AddObject("ingridient", ingridient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the measure EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomeasure(measure measure)
        {
            base.AddObject("measure", measure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the order_stuff EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorder_stuff(order_stuff order_stuff)
        {
            base.AddObject("order_stuff", order_stuff);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ordert EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToordert(ordert ordert)
        {
            base.AddObject("ordert", ordert);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recipe EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecipe(recipe recipe)
        {
            base.AddObject("recipe", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recipe_stuff EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecipe_stuff(recipe_stuff recipe_stuff)
        {
            base.AddObject("recipe_stuff", recipe_stuff);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the supply EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosupply(supply supply)
        {
            base.AddObject("supply", supply);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the worker EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToworker(worker worker)
        {
            base.AddObject("worker", worker);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new department object.
        /// </summary>
        /// <param name="department_id">Initial value of the department_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static department Createdepartment(global::System.Int32 department_id, global::System.String name)
        {
            department department = new department();
            department.department_id = department_id;
            department.name = name;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 department_id
        {
            get
            {
                return _department_id;
            }
            set
            {
                if (_department_id != value)
                {
                    Ondepartment_idChanging(value);
                    ReportPropertyChanging("department_id");
                    _department_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("department_id");
                    Ondepartment_idChanged();
                }
            }
        }
        private global::System.Int32 _department_id;
        partial void Ondepartment_idChanging(global::System.Int32 value);
        partial void Ondepartment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship10", "worker")]
        public EntityCollection<worker> worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<worker>("cafesystemModel.Relationship10", "worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<worker>("cafesystemModel.Relationship10", "worker", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="food_category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class food_category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new food_category object.
        /// </summary>
        /// <param name="food_category_id">Initial value of the food_category_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static food_category Createfood_category(global::System.Int32 food_category_id, global::System.String name)
        {
            food_category food_category = new food_category();
            food_category.food_category_id = food_category_id;
            food_category.name = name;
            return food_category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 food_category_id
        {
            get
            {
                return _food_category_id;
            }
            set
            {
                if (_food_category_id != value)
                {
                    Onfood_category_idChanging(value);
                    ReportPropertyChanging("food_category_id");
                    _food_category_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("food_category_id");
                    Onfood_category_idChanged();
                }
            }
        }
        private global::System.Int32 _food_category_id;
        partial void Onfood_category_idChanging(global::System.Int32 value);
        partial void Onfood_category_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship15", "recipe")]
        public EntityCollection<recipe> recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipe>("cafesystemModel.Relationship15", "recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipe>("cafesystemModel.Relationship15", "recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="ingridient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ingridient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ingridient object.
        /// </summary>
        /// <param name="ingridient_id">Initial value of the ingridient_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="cost">Initial value of the cost property.</param>
        public static ingridient Createingridient(global::System.Int32 ingridient_id, global::System.String name, global::System.Int32 cost)
        {
            ingridient ingridient = new ingridient();
            ingridient.ingridient_id = ingridient_id;
            ingridient.name = name;
            ingridient.cost = cost;
            return ingridient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ingridient_id
        {
            get
            {
                return _ingridient_id;
            }
            set
            {
                if (_ingridient_id != value)
                {
                    Oningridient_idChanging(value);
                    ReportPropertyChanging("ingridient_id");
                    _ingridient_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ingridient_id");
                    Oningridient_idChanged();
                }
            }
        }
        private global::System.Int32 _ingridient_id;
        partial void Oningridient_idChanging(global::System.Int32 value);
        partial void Oningridient_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private global::System.Int32 _cost;
        partial void OncostChanging(global::System.Int32 value);
        partial void OncostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> measure_id
        {
            get
            {
                return _measure_id;
            }
            set
            {
                Onmeasure_idChanging(value);
                ReportPropertyChanging("measure_id");
                _measure_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("measure_id");
                Onmeasure_idChanged();
            }
        }
        private Nullable<global::System.Int32> _measure_id;
        partial void Onmeasure_idChanging(Nullable<global::System.Int32> value);
        partial void Onmeasure_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> supply_id
        {
            get
            {
                return _supply_id;
            }
            set
            {
                Onsupply_idChanging(value);
                ReportPropertyChanging("supply_id");
                _supply_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("supply_id");
                Onsupply_idChanged();
            }
        }
        private Nullable<global::System.Int32> _supply_id;
        partial void Onsupply_idChanging(Nullable<global::System.Int32> value);
        partial void Onsupply_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship14", "supply")]
        public supply supply
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<supply>("cafesystemModel.Relationship14", "supply").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<supply>("cafesystemModel.Relationship14", "supply").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<supply> supplyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<supply>("cafesystemModel.Relationship14", "supply");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<supply>("cafesystemModel.Relationship14", "supply", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship5", "measure")]
        public measure measure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<measure> measureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<measure>("cafesystemModel.Relationship5", "measure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<measure>("cafesystemModel.Relationship5", "measure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship8", "recipe_stuff")]
        public EntityCollection<recipe_stuff> recipe_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipe_stuff>("cafesystemModel.Relationship8", "recipe_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipe_stuff>("cafesystemModel.Relationship8", "recipe_stuff", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="measure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class measure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new measure object.
        /// </summary>
        /// <param name="measure_id">Initial value of the measure_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static measure Createmeasure(global::System.Int32 measure_id, global::System.String name)
        {
            measure measure = new measure();
            measure.measure_id = measure_id;
            measure.name = name;
            return measure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 measure_id
        {
            get
            {
                return _measure_id;
            }
            set
            {
                if (_measure_id != value)
                {
                    Onmeasure_idChanging(value);
                    ReportPropertyChanging("measure_id");
                    _measure_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("measure_id");
                    Onmeasure_idChanged();
                }
            }
        }
        private global::System.Int32 _measure_id;
        partial void Onmeasure_idChanging(global::System.Int32 value);
        partial void Onmeasure_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship5", "ingridient")]
        public EntityCollection<ingridient> ingridient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ingridient>("cafesystemModel.Relationship5", "ingridient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ingridient>("cafesystemModel.Relationship5", "ingridient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="order_stuff")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order_stuff : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order_stuff object.
        /// </summary>
        /// <param name="order_stuff_id">Initial value of the order_stuff_id property.</param>
        /// <param name="recipe_id">Initial value of the recipe_id property.</param>
        /// <param name="order_id">Initial value of the order_id property.</param>
        public static order_stuff Createorder_stuff(global::System.Int32 order_stuff_id, global::System.Int32 recipe_id, global::System.Int32 order_id)
        {
            order_stuff order_stuff = new order_stuff();
            order_stuff.order_stuff_id = order_stuff_id;
            order_stuff.recipe_id = recipe_id;
            order_stuff.order_id = order_id;
            return order_stuff;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_stuff_id
        {
            get
            {
                return _order_stuff_id;
            }
            set
            {
                if (_order_stuff_id != value)
                {
                    Onorder_stuff_idChanging(value);
                    ReportPropertyChanging("order_stuff_id");
                    _order_stuff_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_stuff_id");
                    Onorder_stuff_idChanged();
                }
            }
        }
        private global::System.Int32 _order_stuff_id;
        partial void Onorder_stuff_idChanging(global::System.Int32 value);
        partial void Onorder_stuff_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_id
        {
            get
            {
                return _recipe_id;
            }
            set
            {
                if (_recipe_id != value)
                {
                    Onrecipe_idChanging(value);
                    ReportPropertyChanging("recipe_id");
                    _recipe_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_id");
                    Onrecipe_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_id;
        partial void Onrecipe_idChanging(global::System.Int32 value);
        partial void Onrecipe_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship19", "recipe")]
        public recipe recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship19", "recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship19", "recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipe> recipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship19", "recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipe>("cafesystemModel.Relationship19", "recipe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship20", "ordert")]
        public ordert ordert
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordert>("cafesystemModel.Relationship20", "ordert").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordert>("cafesystemModel.Relationship20", "ordert").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ordert> ordertReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ordert>("cafesystemModel.Relationship20", "ordert");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ordert>("cafesystemModel.Relationship20", "ordert", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="ordert")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ordert : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ordert object.
        /// </summary>
        /// <param name="order_id">Initial value of the order_id property.</param>
        /// <param name="totalcost">Initial value of the totalcost property.</param>
        /// <param name="date">Initial value of the date property.</param>
        public static ordert Createordert(global::System.Int32 order_id, global::System.Int32 totalcost, global::System.DateTime date)
        {
            ordert ordert = new ordert();
            ordert.order_id = order_id;
            ordert.totalcost = totalcost;
            ordert.date = date;
            return ordert;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_id
        {
            get
            {
                return _order_id;
            }
            set
            {
                if (_order_id != value)
                {
                    Onorder_idChanging(value);
                    ReportPropertyChanging("order_id");
                    _order_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_id");
                    Onorder_idChanged();
                }
            }
        }
        private global::System.Int32 _order_id;
        partial void Onorder_idChanging(global::System.Int32 value);
        partial void Onorder_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 totalcost
        {
            get
            {
                return _totalcost;
            }
            set
            {
                OntotalcostChanging(value);
                ReportPropertyChanging("totalcost");
                _totalcost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalcost");
                OntotalcostChanged();
            }
        }
        private global::System.Int32 _totalcost;
        partial void OntotalcostChanging(global::System.Int32 value);
        partial void OntotalcostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship20", "order_stuff")]
        public EntityCollection<order_stuff> order_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order_stuff>("cafesystemModel.Relationship20", "order_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order_stuff>("cafesystemModel.Relationship20", "order_stuff", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recipe object.
        /// </summary>
        /// <param name="recipe_id">Initial value of the recipe_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static recipe Createrecipe(global::System.Int32 recipe_id, global::System.String name)
        {
            recipe recipe = new recipe();
            recipe.recipe_id = recipe_id;
            recipe.name = name;
            return recipe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_id
        {
            get
            {
                return _recipe_id;
            }
            set
            {
                if (_recipe_id != value)
                {
                    Onrecipe_idChanging(value);
                    ReportPropertyChanging("recipe_id");
                    _recipe_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_id");
                    Onrecipe_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_id;
        partial void Onrecipe_idChanging(global::System.Int32 value);
        partial void Onrecipe_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> food_category_id
        {
            get
            {
                return _food_category_id;
            }
            set
            {
                Onfood_category_idChanging(value);
                ReportPropertyChanging("food_category_id");
                _food_category_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("food_category_id");
                Onfood_category_idChanged();
            }
        }
        private Nullable<global::System.Int32> _food_category_id;
        partial void Onfood_category_idChanging(Nullable<global::System.Int32> value);
        partial void Onfood_category_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> totalcost
        {
            get
            {
                return _totalcost;
            }
            set
            {
                OntotalcostChanging(value);
                ReportPropertyChanging("totalcost");
                _totalcost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalcost");
                OntotalcostChanged();
            }
        }
        private Nullable<global::System.Int32> _totalcost;
        partial void OntotalcostChanging(Nullable<global::System.Int32> value);
        partial void OntotalcostChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship15", "food_category")]
        public food_category food_category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<food_category>("cafesystemModel.Relationship15", "food_category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<food_category>("cafesystemModel.Relationship15", "food_category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<food_category> food_categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<food_category>("cafesystemModel.Relationship15", "food_category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<food_category>("cafesystemModel.Relationship15", "food_category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship19", "order_stuff")]
        public EntityCollection<order_stuff> order_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<order_stuff>("cafesystemModel.Relationship19", "order_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<order_stuff>("cafesystemModel.Relationship19", "order_stuff", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship9", "recipe_stuff")]
        public EntityCollection<recipe_stuff> recipe_stuff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipe_stuff>("cafesystemModel.Relationship9", "recipe_stuff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipe_stuff>("cafesystemModel.Relationship9", "recipe_stuff", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="recipe_stuff")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recipe_stuff : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recipe_stuff object.
        /// </summary>
        /// <param name="ingridient_id">Initial value of the ingridient_id property.</param>
        /// <param name="recipe_id">Initial value of the recipe_id property.</param>
        /// <param name="recipe_stuff_id">Initial value of the recipe_stuff_id property.</param>
        /// <param name="count">Initial value of the count property.</param>
        public static recipe_stuff Createrecipe_stuff(global::System.Int32 ingridient_id, global::System.Int32 recipe_id, global::System.Int32 recipe_stuff_id, global::System.Int32 count)
        {
            recipe_stuff recipe_stuff = new recipe_stuff();
            recipe_stuff.ingridient_id = ingridient_id;
            recipe_stuff.recipe_id = recipe_id;
            recipe_stuff.recipe_stuff_id = recipe_stuff_id;
            recipe_stuff.count = count;
            return recipe_stuff;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ingridient_id
        {
            get
            {
                return _ingridient_id;
            }
            set
            {
                if (_ingridient_id != value)
                {
                    Oningridient_idChanging(value);
                    ReportPropertyChanging("ingridient_id");
                    _ingridient_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ingridient_id");
                    Oningridient_idChanged();
                }
            }
        }
        private global::System.Int32 _ingridient_id;
        partial void Oningridient_idChanging(global::System.Int32 value);
        partial void Oningridient_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_id
        {
            get
            {
                return _recipe_id;
            }
            set
            {
                if (_recipe_id != value)
                {
                    Onrecipe_idChanging(value);
                    ReportPropertyChanging("recipe_id");
                    _recipe_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_id");
                    Onrecipe_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_id;
        partial void Onrecipe_idChanging(global::System.Int32 value);
        partial void Onrecipe_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 recipe_stuff_id
        {
            get
            {
                return _recipe_stuff_id;
            }
            set
            {
                if (_recipe_stuff_id != value)
                {
                    Onrecipe_stuff_idChanging(value);
                    ReportPropertyChanging("recipe_stuff_id");
                    _recipe_stuff_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("recipe_stuff_id");
                    Onrecipe_stuff_idChanged();
                }
            }
        }
        private global::System.Int32 _recipe_stuff_id;
        partial void Onrecipe_stuff_idChanging(global::System.Int32 value);
        partial void Onrecipe_stuff_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private global::System.Int32 _count;
        partial void OncountChanging(global::System.Int32 value);
        partial void OncountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship8", "ingridient")]
        public ingridient ingridient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ingridient> ingridientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ingridient>("cafesystemModel.Relationship8", "ingridient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship9", "recipe")]
        public recipe recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipe> recipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipe>("cafesystemModel.Relationship9", "recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="supply")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class supply : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new supply object.
        /// </summary>
        /// <param name="supply_id">Initial value of the supply_id property.</param>
        /// <param name="count">Initial value of the count property.</param>
        public static supply Createsupply(global::System.Int32 supply_id, global::System.Int32 count)
        {
            supply supply = new supply();
            supply.supply_id = supply_id;
            supply.count = count;
            return supply;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 supply_id
        {
            get
            {
                return _supply_id;
            }
            set
            {
                if (_supply_id != value)
                {
                    Onsupply_idChanging(value);
                    ReportPropertyChanging("supply_id");
                    _supply_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("supply_id");
                    Onsupply_idChanged();
                }
            }
        }
        private global::System.Int32 _supply_id;
        partial void Onsupply_idChanging(global::System.Int32 value);
        partial void Onsupply_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private global::System.Int32 _count;
        partial void OncountChanging(global::System.Int32 value);
        partial void OncountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship14", "ingridient")]
        public EntityCollection<ingridient> ingridient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ingridient>("cafesystemModel.Relationship14", "ingridient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ingridient>("cafesystemModel.Relationship14", "ingridient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cafesystemModel", Name="worker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class worker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new worker object.
        /// </summary>
        /// <param name="worker_id">Initial value of the worker_id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="department_id">Initial value of the department_id property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static worker Createworker(global::System.Int32 worker_id, global::System.String name, global::System.Int32 department_id, global::System.String password)
        {
            worker worker = new worker();
            worker.worker_id = worker_id;
            worker.name = name;
            worker.department_id = department_id;
            worker.password = password;
            return worker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 worker_id
        {
            get
            {
                return _worker_id;
            }
            set
            {
                if (_worker_id != value)
                {
                    Onworker_idChanging(value);
                    ReportPropertyChanging("worker_id");
                    _worker_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("worker_id");
                    Onworker_idChanged();
                }
            }
        }
        private global::System.Int32 _worker_id;
        partial void Onworker_idChanging(global::System.Int32 value);
        partial void Onworker_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cellphone
        {
            get
            {
                return _cellphone;
            }
            set
            {
                OncellphoneChanging(value);
                ReportPropertyChanging("cellphone");
                _cellphone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cellphone");
                OncellphoneChanged();
            }
        }
        private global::System.String _cellphone;
        partial void OncellphoneChanging(global::System.String value);
        partial void OncellphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 department_id
        {
            get
            {
                return _department_id;
            }
            set
            {
                if (_department_id != value)
                {
                    Ondepartment_idChanging(value);
                    ReportPropertyChanging("department_id");
                    _department_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("department_id");
                    Ondepartment_idChanged();
                }
            }
        }
        private global::System.Int32 _department_id;
        partial void Ondepartment_idChanging(global::System.Int32 value);
        partial void Ondepartment_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cafesystemModel", "Relationship10", "department")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("cafesystemModel.Relationship10", "department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("cafesystemModel.Relationship10", "department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("cafesystemModel.Relationship10", "department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("cafesystemModel.Relationship10", "department", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
